services:
  postgres:
    image: 'postgres:16-alpine'
    container_name: products-postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: myuser
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser -d mydatabase" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - products-network

volumes:
  postgres-data:

networks:
  products-network:
    driver: bridge
